### ISSUE TITLE
Water mesh becomes invalid during minimap draw

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#210]
```
System.InvalidOperationException was unhandled
 _HResult=-2146233079
 _message=A valid vertex buffer (and a valid index buffer if you are using indexed primitives) must be set on the device before any draw operations may be performed.
 HResult=-2146233079
 IsTransient=false
 Message=A valid vertex buffer (and a valid index buffer if you are using indexed primitives) must be set on the device before any draw operations may be performed.
 Source=Microsoft.Xna.Framework.Graphics
 StackTrace:
      at Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw(Boolean bUserPrimitives, Boolean bIndexedPrimitives)
      at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(PrimitiveType primitiveType, Int32 baseVertex, Int32 minVertexIndex, Int32 numVertices, Int32 startIndex, Int32 primitiveCount)
      at DwarfCorp.GeometricPrimitive.Render(GraphicsDevice device) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Graphics\Primitives\GeometricPrimitive.cs:line 139
      at DwarfCorp.WaterRenderer.DrawWaterFlat(GraphicsDevice device, Matrix view, Matrix projection, Shader effect, ChunkManager chunks) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Graphics\Effects\WaterRenderer.cs:line 218
      at DwarfCorp.Gui.Widgets.MinimapRenderer.PreRender(DwarfTime time, SpriteBatch sprites) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Gui\Widgets\Minimap.cs:line 202
      at DwarfCorp.GameStates.PlayState.Render(DwarfTime gameTime) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 354
      at DwarfCorp.GameStates.GameStateManager.Render(DwarfTime time) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\GameStateManager.cs:line 149
      at DwarfCorp.DwarfGame.Draw(GameTime time) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\DwarfGame.cs:line 310
      at Microsoft.Xna.Framework.Game.DrawFrame()
      at Microsoft.Xna.Framework.Game.Tick()
      at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
      at Microsoft.Xna.Framework.GameHost.OnIdle()
      at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
      at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
      at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
      at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
      at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
      at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
      at System.Windows.Forms.Application.Run(Form mainForm)
      at Microsoft.Xna.Framework.WindowsGameHost.Run()
      at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
      at Microsoft.Xna.Framework.Game.Run()
      at DwarfCorp.Program.Main(String[] args) in c:\Users\W\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Program.cs:line 7
```

**Comment by mklingen** [comment]
fixed on my branch
