### ISSUE TITLE
Null reference in world generator state popped. Unhandeled exception in world genreator

### ISSUE THREAD

**Issue by Aikhjarto** [CompletelyFairGames/dwarfcorp#356]
While playing around in the world generator, the game crashed and I got an unhandeled exception error in the eventlog of Windows.

```
Application: DwarfCorp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DwarfCorp.GameStates.WorldGeneratorState.OnPopped()
   at DwarfCorp.GameStates.GameStateManager.Update(DwarfCorp.DwarfTime)
   at DwarfCorp.DwarfGame.Update(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(System.Object, System.EventArgs)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(System.Object, System.EventArgs)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean)
   at DwarfCorp.Program.Main(System.String[])
```

**Comment by mklingen** [comment]
Fixed by https://github.com/CompletelyFairGames/dwarfcorp/commit/9633c66e4bf7106e8ec2a0a6a22e485cce2cfc90 will be in the patch.
