### ISSUE TITLE
User experienced crash on game exit. Null reference in GetMoveActions.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#421]
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DwarfCorp.CreatureMovement+<GetMoveActions>d33.MoveNext()
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[DwarfCorp.MoveAction, DwarfCorp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at DwarfCorp.CreatureMovement+<GetInverseMoveActions>d35.MoveNext()
   at DwarfCorp.AStarPlanner.InversePath(DwarfCorp.CreatureMovement, DwarfCorp.VoxelHandle, DwarfCorp.GoalRegion, DwarfCorp.ChunkManager, Int32, System.Collections.Generic.List1<DwarfCorp.MoveAction> ByRef, Single)
   at DwarfCorp.AStarPlanner.FindPath(DwarfCorp.CreatureMovement, DwarfCorp.VoxelHandle, DwarfCorp.GoalRegion, DwarfCorp.ChunkManager, Int32, Single)
   at DwarfCorp.PlanService.HandleRequest(DwarfCorp.AstarPlanRequest)
   at DwarfCorp.Service2[[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Update()
   at DwarfCorp.Service`2[[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ServiceThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by mklingen** [comment]
Fixed in the recent build using my suggestion. Still not desirable but much better.
