### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by Searthh** [CompletelyFairGames/dwarfcorp#422]
2 error logs at the same time.
Unfortunately, my computer speaks Dutch instead of English.

**First one:**

Logboeknaam:   Application
Bron:          .NET Runtime
Datum:         22/10/2017 0:45:53
Gebeurtenis-id:1026
Taakcategorie: Geen
Niveau:        Fout
Trefwoorden:   Klassiek
Gebruiker:     n.v.t.
Computer:      Galadriel
Beschrijving:
Application: DwarfCorp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces(Microsoft.Xna.Framework.Graphics.GraphicsDevice)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(Microsoft.Xna.Framework.Graphics.GraphicsDevice, Int32, Int32, Boolean, Microsoft.Xna.Framework.Graphics.SurfaceFormat, Microsoft.Xna.Framework.Graphics.DepthFormat, Int32, Microsoft.Xna.Framework.Graphics.RenderTargetUsage)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(Microsoft.Xna.Framework.Graphics.GraphicsDevice, Int32, Int32, Boolean, Microsoft.Xna.Framework.Graphics.SurfaceFormat, Microsoft.Xna.Framework.Graphics.DepthFormat, Int32, Microsoft.Xna.Framework.Graphics.RenderTargetUsage)
   at DwarfCorp.WorldManager.GraphicsPreparingDeviceSettings(System.Object, Microsoft.Xna.Framework.PreparingDeviceSettingsEventArgs)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.OnPreparingDeviceSettings(System.Object, Microsoft.Xna.Framework.PreparingDeviceSettingsEventArgs)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(Microsoft.Xna.Framework.GraphicsDeviceInformation)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ChangeDevice(Boolean)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.EnsureDevicePlatform()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.BeginDraw()
   at Microsoft.Xna.Framework.Game.BeginDraw()
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Paint(System.Object, System.EventArgs)
   at Microsoft.Xna.Framework.GameWindow.OnPaint()
   at Microsoft.Xna.Framework.WindowsGameWindow.mainForm_Paint(System.Object, System.Windows.Forms.PaintEventArgs)

Exception Info: System.InvalidOperationException
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(System.Object, System.EventArgs)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.RunDialog(System.Windows.Forms.Form)
   at System.Windows.Forms.Form.ShowDialog(System.Windows.Forms.IWin32Window)
   at System.Windows.Forms.Form.ShowDialog()
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at Microsoft.Xna.Framework.Input.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, UInt32, IntPtr, IntPtr)
   at Microsoft.Xna.Framework.Input.WindowMessageHooker+Hook.WndProc(IntPtr, UInt32, IntPtr, IntPtr)

Gebeurtenis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-21T22:45:53.030312000Z" />
    <EventRecordID>5723</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Galadriel</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: DwarfCorp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces(Microsoft.Xna.Framework.Graphics.GraphicsDevice)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(Microsoft.Xna.Framework.Graphics.GraphicsDevice, Int32, Int32, Boolean, Microsoft.Xna.Framework.Graphics.SurfaceFormat, Microsoft.Xna.Framework.Graphics.DepthFormat, Int32, Microsoft.Xna.Framework.Graphics.RenderTargetUsage)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(Microsoft.Xna.Framework.Graphics.GraphicsDevice, Int32, Int32, Boolean, Microsoft.Xna.Framework.Graphics.SurfaceFormat, Microsoft.Xna.Framework.Graphics.DepthFormat, Int32, Microsoft.Xna.Framework.Graphics.RenderTargetUsage)
   at DwarfCorp.WorldManager.GraphicsPreparingDeviceSettings(System.Object, Microsoft.Xna.Framework.PreparingDeviceSettingsEventArgs)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.OnPreparingDeviceSettings(System.Object, Microsoft.Xna.Framework.PreparingDeviceSettingsEventArgs)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(Microsoft.Xna.Framework.GraphicsDeviceInformation)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ChangeDevice(Boolean)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.EnsureDevicePlatform()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.BeginDraw()
   at Microsoft.Xna.Framework.Game.BeginDraw()
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Paint(System.Object, System.EventArgs)
   at Microsoft.Xna.Framework.GameWindow.OnPaint()
   at Microsoft.Xna.Framework.WindowsGameWindow.mainForm_Paint(System.Object, System.Windows.Forms.PaintEventArgs)

Exception Info: System.InvalidOperationException
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(System.Object, System.EventArgs)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.RunDialog(System.Windows.Forms.Form)
   at System.Windows.Forms.Form.ShowDialog(System.Windows.Forms.IWin32Window)
   at System.Windows.Forms.Form.ShowDialog()
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.Control+ControlNativeWindow.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at Microsoft.Xna.Framework.Input.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, UInt32, IntPtr, IntPtr)
   at Microsoft.Xna.Framework.Input.WindowMessageHooker+Hook.WndProc(IntPtr, UInt32, IntPtr, IntPtr)

</Data>
  </EventData>
</Event>

**Second one:**

Logboeknaam:   Application
Bron:          Application Error
Datum:         22/10/2017 0:45:53
Gebeurtenis-id:1000
Taakcategorie: (100)
Niveau:        Fout
Trefwoorden:   Klassiek
Gebruiker:     n.v.t.
Computer:      Galadriel
Beschrijving:
Naam van toepassing met fout: DwarfCorp.exe, versie: 1.0.0.0, tijdstempel: 0x59e40b92
Naam van module met fout: KERNELBASE.dll, versie: 10.0.15063.674, tijdstempel: 0x6d16dd24
Uitzonderingscode: 0xe0434352
Foutmarge: 0x000eb872
Id van proces met fout: 0x19f0
Starttijd van toepassing met fout: 0x01d34aaef566ed89
Pad naar toepassing met fout: C:\Users\dries\Desktop\Games\DwarfCorp\DwarfCorp.exe
Pad naar module met fout: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: d5c84dd8-0919-43e3-af01-f4d755ef2fc9
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 
Gebeurtenis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-21T22:45:53.282464000Z" />
    <EventRecordID>5724</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Galadriel</Computer>
    <Security />
  </System>
  <EventData>
    <Data>DwarfCorp.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>59e40b92</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.15063.674</Data>
    <Data>6d16dd24</Data>
    <Data>e0434352</Data>
    <Data>000eb872</Data>
    <Data>19f0</Data>
    <Data>01d34aaef566ed89</Data>
    <Data>C:\Users\dries\Desktop\Games\DwarfCorp\DwarfCorp.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>d5c84dd8-0919-43e3-af01-f4d755ef2fc9</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by com1clyf3** [comment]
This crash still occurs: 
![image](https://user-images.githubusercontent.com/6562812/39284236-50ada3c8-48e0-11e8-933a-9c45b6eb7c6e.png)

Mine specifically first went to a purple screen for a few seconds, then crashed to desktop with a crash log.

Repro:
1. Open game in windowed mode.
2. Start a game of any kind.
3. Minimize window.
4. Lock computer (Windows button + L for shortcut)
5. Log back in.
6. Open game window.
7. Observe crash.
 
Log:
[201804252327363947_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/1949599/201804252327363947_Crashlog.txt)

40d844c8

**Comment by com1clyf3** [comment]
Small update, likely unrelated and its own separate bug,  but playing for a few minutes in windowed mode, clicking away to do something else for a few minutes, and then opening the game again has been leading to purple screen of death. Not always, but pretty often. Most likely related to the current build instability overall.
