### ISSUE TITLE
Unable to save & auto save game

### ISSUE THREAD

**Issue by PaxJaromeMalues** [CompletelyFairGames/dwarfcorp#728]
Fresh install.
After an hour of play and auto saves suddely the message:
Save failed! - Object reference not set to an instance of an object
appears.
Manual save also not possible.

**Comment by mklingen** [comment]
Is this all the time, or just once? Can you find anything in `C/Users/<your_username>/AppData/Roaming/DwarfCorp/log.txt`?

**Comment by PaxJaromeMalues** [comment]
Yip, it is mentioned in there all the time, basically on every autosave attempt.
Here is one instance:

`Overworld C:\Users\<herpaderp>\AppData\Roaming\DwarfCorp\Worlds\Volcano Reaches\world.png already exists. Just assuming it is correct.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DwarfCorp.Task.Equals(Object obj) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\TaskManagement\Task.cs:line 118
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.List`1.Contains(T item)`

`C:\Users\matth\Desktop`

smile

**Comment by PaxJaromeMalues** [comment]
There is also this at the end of the log:

```
   at DwarfCorp.FileUtils.Save[T](JsonSerializer serializer, T obj, String filePath, Boolean compress) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\AssetManagement\FileUtils-SaveJson.cs:line 169
   at DwarfCorp.SaveGame.WriteFile(String directory) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\AssetManagement\GameSave\SaveGame.cs:line 55
   at DwarfCorp.WorldManager.SaveThreadRoutine(String filename) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\World\WorldManager.cs:line 604
```

**Comment by mklingen** [comment]
Okay, this is an instance of https://github.com/CompletelyFairGames/dwarfcorp/issues/697, which has been fixed. Should make it into the release by the end of the week.
