### ISSUE TITLE
Crash: UnhandledException in CreatureMovement / Teleport

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#951]
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at DwarfCorp.CreatureMovement.<GetMoveActions>d__43.MoveNext() in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Components\AI\CreatureMovement.cs:line 361
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at DwarfCorp.CreatureMovement.<GetInverseMoveActions>d__47.MoveNext() in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Components\AI\CreatureMovement.cs:line 884
   at DwarfCorp.AStarPlanner.InversePath(CreatureMovement mover, VoxelHandle startVoxel, GoalRegion goal, ChunkManager chunks, Int32 maxExpansions, List`1& toReturn, Single weight, Func`1 continueFunc) in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Tools\Planning\AStarPlanner.cs:line 514
   at DwarfCorp.AStarPlanner.FindPath(CreatureMovement mover, VoxelHandle start, GoalRegion goal, ChunkManager chunks, Int32 maxExpansions, Single weight, Int32 numPlans, Func`1 continueFunc, PlanResultCode& resultCode) in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Tools\Planning\AStarPlanner.cs:line 674
   at DwarfCorp.PlanService.HandleRequest(AstarPlanRequest req) in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Tools\Planning\PlanService.cs:line 90
   at DwarfCorp.Service`2.Update() in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Tools\ServiceArchitecture\Service.cs:line 196
   at DwarfCorp.Service`2.ServiceThread() in C:\Users\kingofarabi1\Source\Repos\dwarfcorp\DwarfCorp\DwarfCorpXNA\Tools\ServiceArchitecture\Service.cs:line 166
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

![image](https://user-images.githubusercontent.com/6562812/47403023-f638c200-d715-11e8-8a1d-a362797854c7.png)

Occurred seemingly randomly during natural play in 
[Giruholand_34_131847996771433191.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2508824/Giruholand_34_131847996771433191.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2508825/Giruholand.zip)

27c42f81

**Comment by mklingen** [comment]
Problem is that path finding is in a thread. Solution is to convert that enumerable into a list.

**Comment by com1clyf3** [comment]
Got this crash out of cf5eaf96 if you need more info.

[Giruholand_34_131848078536128574.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2512300/Giruholand_34_131848078536128574.zip)
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2512301/Giruholand.zip)

1. Load save.
2. Pause.
3. Hire ten dwarves at once.
4. Unpause game and move camera around to stress system. FPS was floating at 0-2 FPS for about ten seconds, so crash was clearly pretty close. 
5. Observe crash.
