### ISSUE TITLE
Saving a game manually disables autosave

### ISSUE THREAD

**Issue by PaxJaromeMalues** [CompletelyFairGames/dwarfcorp#981]
Hi, I just saw that playing the game and then saving manually once will end up in the game not being able to recover old autosaves, even tho the file autosave process still continued ingame for ~45mins every 5 minutes.
THis is relevant because crashes will then leaver you with about hours old manual saves instead of the recent latest autosave.

**Comment by mklingen** [comment]
I can't seem to reproduce this. Saving manually does not seem to disable autosave. Can you maybe clarify what you mean by "recover old autosaves"? Are you saying that your auto saves are not loading properly, or that they aren't appearing? FYI, dwarfcorp keeps around 1 autosave, and as many manual saves as you want.

**Comment by PaxJaromeMalues** [comment]
This occured to me while playing a normal session (still with the bed-bug).
1. Play normally with 5min autosave.
2. Random Crash.
3. Reload savegame from autosave.
4. Repeat step 2 and 3 for n times.
5. Decide to make a manual save.
6. Random Crash.
7. Restart game.
8. Empty load area, no manual save present, no autosave files present.
MFW     (⊙ ‿ ⊙)  ? plS wAt?

Might just be a random fuckup of my computer.
Haven't had time to play since.

**Comment by PaxJaromeMalues** [comment]
Oh wait, just remembered, false order:

1. Play normally with 5min autosave.
2. Random Crash.
3. Reload savegame from autosave.
4. Repeat step 2 and 3 for n times.
5. Decide to make a manual save.
6. Random Crash.
7. Restart game.
8. Load game from manual save file.
9. auto saves continue ingame like normal.
10. Random Crash.
11. Restart game.
12.  (⊙ ‿ ⊙) ? plS wAt? When last autosave file is older than 1 hour despide the game continuing to autosave cycle like regular.

**Comment by mklingen** [comment]
> Random Crash.

Okay, this is the real bug. Was there any kind of message printed when the game crashed? If the game is crashing it's possible or even likely that it was autosaving that caused the crash.

**Comment by mklingen** [comment]
Also, when loading a game it tells you which directory it's loading from. If you could navigate to that directory, is there anything in it?

**Comment by PaxJaromeMalues** [comment]
The only thing in there is the autosave file from the game from yesterday where I died awfully by being supersnaked. Drive has 25GB free and there was no crash message displayed. I only get crash messages very very rarely. Usually the game just ends abruptly and throws me back to the Win10 desktop.

**Comment by PaxJaromeMalues** [comment]
Ok I continued to play another round and I got to say that autosave malfunctioned again. Saves every 5 mins -> crash -> oldest save from 36minutes ago. IDK what this is.

**Comment by mklingen** [comment]
when you say the game crashed, that was a crash to desktop with no popup window with an exception?

**Comment by PaxJaromeMalues** [comment]
```DwarfCorp Version 19.01.08_XNA
OS Version: 6.2.9200.0
OS Platform: Win32NT
OS SP: 
OS Version String: Microsoft Windows NT 6.2.9200.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at DwarfCorp.Scripting.Gambling.PushParticipants() in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Gambling.cs:line 156
   at DwarfCorp.Scripting.Gambling.Update(DwarfTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Gambling.cs:line 204
   at DwarfCorp.GameMaster.Update(DwarfGame game, DwarfTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Scripting\Player\GameMaster.cs:line 448
   at DwarfCorp.WorldManager.Update(DwarfTime gameTime) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\World\WorldManager.cs:line 581
   at DwarfCorp.GameStates.PlayState.Update(DwarfTime gameTime) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\PlayState.cs:line 289
   at DwarfCorp.GameStates.GameStateManager.Update(DwarfTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\GameStates\GameStateManager.cs:line 132
   at DwarfCorp.DwarfGame.Update(GameTime time) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\DwarfGame.cs:line 604
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at DwarfCorp.Program.Main(String[] args) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Program.cs:line 88
```

That is the last crash message I received.
Also the first time I received any crash including a popup when it crashed! Usually it just drops back to the windows desktop w/o any notification whatsoever.

**Comment by PaxJaromeMalues** [comment]
In that case I have no idea what the autosave issue could be :/
