### ISSUE TITLE
Race condition while rebuilding voxels.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#989]
If voxels are getting rebuilt, and at the same time a creature gets killed, this race condition can occur.

```
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at DwarfCorp.GameComponent.ReceiveMessageRecursive(Message messageToReceive) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Components\GameComponent.cs:line 156
   at DwarfCorp.VoxelChunk.Rebuild(GraphicsDevice g) in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Voxels\VoxelChunk.cs:line 172
   at DwarfCorp.ChunkManager.RebuildVoxelsThread() in C:\Users\matth\Desktop\dwarfcorp\DwarfCorp\DwarfCorpXNA\Voxels\ChunkManager.cs:line 196```
on 13. Dec 2018

```

Reported in #981

**Comment by mklingen** [comment]
Fixed.
